---
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
    - ip: 10.131.10.196
    ports:
    - port: 1
  - addresses:
    - ip: 10.131.29.59
    ports:
    - port: 1
