apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "glusterfs-claim"
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: "8Gi"
  selector:
    matchLabels:
      type: "static_upload"