apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "gluster-default-volume"
spec:
  capacity:
   storage: "8Gi"
  accessModes:
  - "ReadWriteMany"
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "uploads_static"
    readOnly: false
  persistentVolumeReclaimPolicy: "Retain"
