apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "gluster-default-volume"
  labels:
    type: static_upload
spec:
  capacity:
    storage: "8Gi"
  accessModes:
  - "ReadWriteMany"
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "static_upload"
    readOnly: false
  persistentVolumeReclaimPolicy: "Retain"